# Generated by Django 3.2.12 on 2023-11-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_data_de_execucao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='data_de_execucao',
        ),
        migrations.AlterField(
            model_name='task',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
